/**
 * 30일 주제 큐 — day 1 은 3번째 글이다.
 *
 * 이 파일은 drafts 전용이다. 런타임에서 import 하지 않는다.
 * 큐는 사람이 만들고 사람이 고친다. AI 가 주제를 스스로 정하지 않는다
 * (제작 전략 §9.1 — 우나어의 "트렌드 제안 기반 자동 생성"으로 돌아가는 경로).
 *
 * 읽기용 요약본: docs/operations/2026-08-23-soransoran-magazine-seo-production-strategy.md §8
 * 검수 깊이 정의: docs/operations/2026-08-23-soransoran-magazine-strategy.md 원칙 5 · §5.1
 */
import type { MagazineCluster } from '@/content/magazine/types'

/** 검수 깊이를 정한다. 등급을 낮출 수 없는 조건은 매거진 전략 §5.2. */
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH'

/** riskLevel 에서 파생되지만, 자동 QA FAIL 이면 FULL_REVIEW 로 승격된다. */
export type ReviewMode = 'SUMMARY_ONLY' | 'RISK_SENTENCES' | 'FULL_REVIEW'

/** hero 가 없으면 og:image 키가 생략되고 twitter:card 가 summary 로 떨어진다. */
export type ImageNeed = 'REQUIRED' | 'OPTIONAL' | 'NO_IMAGE'

export type SearchIntent = '질문' | '방법' | '비교' | '계산' | '상황'

/** 내부 경로만 쓴다. 외부 링크는 본문에도 큐에도 두지 않는다. */
export type CtaTarget = '/community/menopause' | '/community/free'

export type TopicQueueItem = {
  day: number
  title: string
  /** 영문 kebab-case. 발행 시 articles.ts 의 레코드 key 가 된다 */
  slug: string
  cluster: MagazineCluster
  /** 없으면 단발 글 */
  seriesId?: string
  /** 같은 seriesId 안에서 유일 */
  seriesOrder?: number
  searchIntent: SearchIntent
  targetReader: string
  riskLevel: RiskLevel
  reviewMode: ReviewMode
  imageNeeded: ImageNeed
  ctaTarget: CtaTarget
  /** 본문·하단에서 이을 대상. 메뉴 링크가 아니라 contextual 링크다 */
  internalLinks: string[]
  whyNow: string
  notes: string
}

/** 이미 발행됨 — 큐에 넣지 않는다. menopause-basic 의 다음 order 는 3이다. */
export const PUBLISHED_SLUGS = ['when-does-menopause-start', 'menopause-waking-up-at-3am'] as const

export const TOPIC_QUEUE: TopicQueueItem[] = [
  {
    day: 1,
    title: '갱년기 안면홍조 언제까지 계속되나요',
    slug: 'hot-flash-how-long',
    cluster: 'menopause-symptom',
    seriesId: 'menopause-basic',
    seriesOrder: 3,
    searchIntent: '질문',
    targetReader: '40대 후반~50대 중반',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'REQUIRED',
    ctaTarget: '/community/menopause',
    internalLinks: ['menopause-waking-up-at-3am', 'when-does-menopause-start'],
    whyNow: '시리즈 재개. "언제까지"가 이 시기 가장 큰 불안이다',
    notes: '지속 기간을 숫자로 단정하지 않는다. 사람마다 다르다는 점을 먼저 둔다',
  },
  {
    day: 2,
    title: '나이 들면 잠이 줄어드는 게 정상인가요',
    slug: 'less-sleep-with-age',
    cluster: 'sleep',
    seriesId: 'sleep-series',
    seriesOrder: 1,
    searchIntent: '질문',
    targetReader: '50대 전반',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'REQUIRED',
    ctaTarget: '/community/menopause',
    internalLinks: ['menopause-waking-up-at-3am'],
    whyNow: '새 시리즈 1편. 2편(새벽 3시)에서 자연스럽게 이어진다',
    notes: '시리즈 첫 편이라 전문 검수 대상이다(전략 §5.2). 이후 4편의 톤을 정한다',
  },
  {
    day: 3,
    title: '국민연금 조기수령 60세와 65세 어느 쪽이 유리한가요',
    slug: 'pension-early-vs-normal',
    cluster: 'money-work',
    searchIntent: '비교',
    targetReader: '50대 후반~60대 중반',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/free',
    internalLinks: [],
    whyNow: '건강 편중을 초반에 완화한다. 돈·일 축 첫 진입',
    notes: '제도·수치는 범위로만. 구체 수령액 계산은 HIGH 로 올라간다',
  },
  {
    day: 4,
    title: '갱년기 이유 없이 눈물이 날 때',
    slug: 'menopause-tears',
    cluster: 'emotion',
    searchIntent: '상황',
    targetReader: '40대 중반~50대',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['when-does-menopause-start'],
    whyNow: 'emotion 클러스터 첫 진입. 댓글 유발 상위 후보',
    notes: '새 클러스터 첫 글이라 전문 검수. 우울증으로 단정하지 않는다',
  },
  {
    day: 5,
    title: '갱년기 이후 살이 잘 안 빠지는 이유',
    slug: 'weight-harder-after-menopause',
    cluster: 'daily',
    seriesId: 'body-change',
    seriesOrder: 1,
    searchIntent: '질문',
    targetReader: '40대 후반~50대',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'REQUIRED',
    ctaTarget: '/community/menopause',
    internalLinks: ['when-does-menopause-start'],
    whyNow: 'body-change 시리즈 1편. 체중은 검색량이 크고 이탈이 적다',
    notes: '시리즈 첫 편이라 전문 검수. 특정 다이어트법·보조제 권유 금지',
  },
  {
    day: 6,
    title: '남편이 갱년기를 이해 못 할 때',
    slug: 'husband-doesnt-understand',
    cluster: 'family',
    searchIntent: '상황',
    targetReader: '40대 중반~50대',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/free',
    internalLinks: ['when-does-menopause-start'],
    whyNow: '공감형. 커뮤니티 전환율이 가장 높을 유형이다',
    notes: '남편을 비난하는 톤으로 흐르지 않게 한다',
  },
  {
    day: 7,
    title: '자다가 식은땀으로 깰 때',
    slug: 'night-sweats-waking',
    cluster: 'sleep',
    seriesId: 'sleep-series',
    seriesOrder: 2,
    searchIntent: '상황',
    targetReader: '40대 후반~50대 중반',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['less-sleep-with-age', 'menopause-waking-up-at-3am'],
    whyNow: '2편에서 한 줄로만 언급한 식은땀을 펼친다',
    notes: '침구·온도 조절까지. 약이나 호르몬 치료로 넘어가지 않는다',
  },
  {
    day: 8,
    title: '갱년기 관절이 아픈데 운동해도 되나요',
    slug: 'menopause-joint-pain-exercise',
    cluster: 'menopause-symptom',
    seriesId: 'menopause-basic',
    seriesOrder: 4,
    searchIntent: '질문',
    targetReader: '50대 전반',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['hot-flash-how-long'],
    whyNow: '아파서 못 움직이는 상태가 체중·수면으로 번진다',
    notes: '운동 강도를 처방하지 않는다. "아프면 멈추세요"를 명시한다',
  },
  {
    day: 9,
    title: '50대 재취업 어디부터 알아봐야 하나요',
    slug: 'rehire-where-to-start',
    cluster: 'money-work',
    searchIntent: '방법',
    targetReader: '50대 전반',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/free',
    internalLinks: ['pension-early-vs-normal'],
    whyNow: '돈·일 축 강화. 방향 제시라 위험이 낮다',
    notes: '특정 업체·플랫폼을 지목하지 않는다',
  },
  {
    day: 10,
    title: '갱년기 증상 무슨 과에 가야 하나요',
    slug: 'which-clinic-menopause',
    cluster: 'clinic',
    searchIntent: '질문',
    targetReader: '40대 후반~60대',
    riskLevel: 'HIGH',
    reviewMode: 'FULL_REVIEW',
    imageNeeded: 'REQUIRED',
    ctaTarget: '/community/menopause',
    internalLinks: ['when-does-menopause-start', 'hot-flash-how-long'],
    whyNow: '검색량 최상위. clinic 클러스터 첫 진입',
    notes: 'HIGH — 과 선택은 정보 제공까지만. "가야 한다/안 가도 된다"를 판단해 주지 않는다',
  },
  {
    day: 11,
    title: '갱년기 피부가 갑자기 건조해질 때',
    slug: 'dry-skin-menopause',
    cluster: 'daily',
    seriesId: 'body-change',
    seriesOrder: 2,
    searchIntent: '상황',
    targetReader: '40대 후반~50대',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['weight-harder-after-menopause'],
    whyNow: '피부는 8개 클러스터에 없지만 실제 검색이 많다',
    notes: '제품·성분을 언급하지 않는다. 광고로 읽히는 순간 신뢰를 잃는다',
  },
  {
    day: 12,
    title: '낮잠이 밤잠을 방해할까요',
    slug: 'does-nap-affect-sleep',
    cluster: 'sleep',
    seriesId: 'sleep-series',
    seriesOrder: 3,
    searchIntent: '질문',
    targetReader: '50대~60대',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['night-sweats-waking'],
    whyNow: '시리즈 중간에 가벼운 편을 두어 호흡을 조절한다',
    notes: '낮잠을 금지하는 톤으로 가지 않는다',
  },
  {
    day: 13,
    title: '50대에 친구가 줄어드는 이유',
    slug: 'fewer-friends-50s',
    cluster: 'relationship',
    searchIntent: '질문',
    targetReader: '50대 전반',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'REQUIRED',
    ctaTarget: '/community/free',
    internalLinks: ['husband-doesnt-understand'],
    whyNow: 'relationship 첫 진입. 주간 대표글로 이미지를 붙인다',
    notes: '새 클러스터 첫 글이라 전문 검수. 외로움을 문제로 규정하지 않는다',
  },
  {
    day: 14,
    title: '뱃살만 늘어나는 것 같을 때',
    slug: 'belly-fat-menopause',
    cluster: 'daily',
    seriesId: 'body-change',
    seriesOrder: 3,
    searchIntent: '상황',
    targetReader: '40대 후반~50대',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['weight-harder-after-menopause'],
    whyNow: '체중 롱테일. 5일 글에서 자연스럽게 이어진다',
    notes: '부위별 감량이 가능하다고 말하지 않는다',
  },
  {
    day: 15,
    title: '퇴직 후 건강보험료는 얼마나 나오나요',
    slug: 'health-insurance-after-retire',
    cluster: 'money-work',
    searchIntent: '계산',
    targetReader: '50대 후반~60대',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/free',
    internalLinks: ['pension-early-vs-normal'],
    whyNow: '고지서를 받고 놀라는 시점이 실제로 온다',
    notes: '구체 금액이 아니라 산정 방식과 범위까지. 금액을 못 박으면 HIGH 다',
  },
  {
    day: 16,
    title: '요즘 아무것도 하기 싫을 때',
    slug: 'no-motivation-50s',
    cluster: 'emotion',
    searchIntent: '상황',
    targetReader: '40대 중반~50대',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['menopause-tears'],
    whyNow: '무기력은 말 꺼내기 가장 어려운 증상이다',
    notes: '무기력과 우울증을 뒤섞지 않는다. 상담 권장 문구를 짧게 둔다',
  },
  {
    day: 17,
    title: '잠이 안 올 때 하면 안 되는 것',
    slug: 'what-not-to-do-when-cant-sleep',
    cluster: 'sleep',
    seriesId: 'sleep-series',
    seriesOrder: 4,
    searchIntent: '방법',
    targetReader: '40대 후반~60대',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['does-nap-affect-sleep', 'menopause-waking-up-at-3am'],
    whyNow: '"하지 말 것" 형식은 실행 문턱이 낮다',
    notes: '수면제를 언급하지 않는다. 술을 수면 보조로 다루지 않는다',
  },
  {
    day: 18,
    title: '50대 건강검진 꼭 챙겨야 할 항목',
    slug: 'checkup-items-50s',
    cluster: 'clinic',
    searchIntent: '방법',
    targetReader: '50대 전반',
    riskLevel: 'HIGH',
    reviewMode: 'FULL_REVIEW',
    imageNeeded: 'REQUIRED',
    ctaTarget: '/community/menopause',
    internalLinks: ['which-clinic-menopause'],
    whyNow: '검진 항목이 너무 많아 무엇을 고를지 모른다',
    notes: 'HIGH — 항목 사실관계 검증 필수. 수치·정상범위는 다루지 않는다',
  },
  {
    day: 19,
    title: '자녀가 독립한 뒤 집이 조용할 때',
    slug: 'empty-nest-quiet',
    cluster: 'family',
    searchIntent: '상황',
    targetReader: '50대 전반',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/free',
    internalLinks: ['husband-doesnt-understand'],
    whyNow: '공감형. 댓글이 붙기 쉬운 주제다',
    notes: '자녀에게 서운함을 표하는 톤으로 흐르지 않게 한다',
  },
  {
    day: 20,
    title: '갱년기에 머리카락이 빠질 때',
    slug: 'hair-loss-menopause',
    cluster: 'menopause-symptom',
    searchIntent: '상황',
    targetReader: '40대 후반~50대',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['dry-skin-menopause'],
    whyNow: '겉으로 보이는 변화라 심리적 타격이 크다',
    notes: '탈모 치료·제품·시술을 권하지 않는다',
  },
  {
    day: 21,
    title: '50대 걷기 하루 몇 분이 적당할까요',
    slug: 'walking-minutes-50s',
    cluster: 'daily',
    searchIntent: '계산',
    targetReader: '50대~60대',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/free',
    internalLinks: ['menopause-joint-pain-exercise'],
    whyNow: '일상 축. 실행 문턱이 가장 낮은 운동이다',
    notes: '숫자는 범위로만. 무릎이 아프면 줄이라는 단서를 단다',
  },
  {
    day: 22,
    title: '갱년기 심장이 두근거릴 때',
    slug: 'palpitations-menopause',
    cluster: 'menopause-symptom',
    searchIntent: '상황',
    targetReader: '40대 후반~50대 중반',
    riskLevel: 'HIGH',
    reviewMode: 'FULL_REVIEW',
    imageNeeded: 'REQUIRED',
    ctaTarget: '/community/menopause',
    internalLinks: ['which-clinic-menopause'],
    whyNow: '심장 걱정으로 검색이 몰리는 증상이다',
    notes: 'HIGH — 최고 위험. 위험 신호(흉통·호흡곤란·실신) 안내를 반드시 넣는다',
  },
  {
    day: 23,
    title: '잠자리 습관을 바꿔 본 2주',
    slug: 'sleep-habit-two-weeks',
    cluster: 'sleep',
    seriesId: 'sleep-series',
    seriesOrder: 5,
    searchIntent: '방법',
    targetReader: '40대 후반~60대',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'REQUIRED',
    ctaTarget: '/community/menopause',
    internalLinks: ['what-not-to-do-when-cant-sleep', 'less-sleep-with-age'],
    whyNow: 'sleep 시리즈 완결. 경험 기록형으로 마무리한다',
    notes: '효과를 보장하지 않는다. "이렇게 해봤다"까지가 끝이다',
  },
  {
    day: 24,
    title: '주부로 지내다 다시 일하려면',
    slug: 'back-to-work-homemaker',
    cluster: 'money-work',
    searchIntent: '방법',
    targetReader: '40대 후반~50대',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/free',
    internalLinks: ['rehire-where-to-start'],
    whyNow: '경력단절 재진입은 우리 타겟의 핵심 고민이다',
    notes: '"늦지 않았다"류의 값싼 위로로 끝내지 않는다',
  },
  {
    day: 25,
    title: '기억력이 떨어진 것 같을 때',
    slug: 'memory-worry-menopause',
    cluster: 'emotion',
    searchIntent: '상황',
    targetReader: '50대 전반',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['no-motivation-50s'],
    whyNow: '치매 걱정으로 이어지는 검색이 많다',
    notes: '치매 불안을 자극하지 않는다. 이 글에서 가장 주의할 지점이다',
  },
  {
    day: 26,
    title: '모임에 나가기 싫어질 때',
    slug: 'avoiding-gatherings',
    cluster: 'relationship',
    searchIntent: '상황',
    targetReader: '50대 전반',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/free',
    internalLinks: ['fewer-friends-50s'],
    whyNow: '사람이 피곤해지는 시기를 있는 그대로 다룬다',
    notes: '사회성을 회복하라고 채근하지 않는다',
  },
  {
    day: 27,
    title: '저녁 식사를 바꿔 본 2주',
    slug: 'dinner-change-two-weeks',
    cluster: 'daily',
    seriesId: 'body-change',
    seriesOrder: 4,
    searchIntent: '방법',
    targetReader: '40대 후반~50대',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['belly-fat-menopause'],
    whyNow: '경험 기록형. 식단 처방을 피하면서 실천을 다룰 수 있다',
    notes: '특정 식단을 처방하지 않는다. 영양제는 언급조차 하지 않는다',
  },
  {
    day: 28,
    title: '퇴직금 IRP에 넣으면 세금이 얼마나 줄어드나요',
    slug: 'irp-tax-benefit',
    cluster: 'money-work',
    searchIntent: '계산',
    targetReader: '50대 후반~60대 중반',
    riskLevel: 'HIGH',
    reviewMode: 'FULL_REVIEW',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/free',
    internalLinks: ['pension-early-vs-normal', 'health-insurance-after-retire'],
    whyNow: '퇴직 시점의 판단이라 늦으면 되돌릴 수 없다',
    notes: 'HIGH — 세제는 틀리면 실제 금전 손해다. 수치·요건 검증 필수',
  },
  {
    day: 29,
    title: '갱년기가 끝나면 몸은 어떻게 달라지나요',
    slug: 'after-menopause-body',
    cluster: 'menopause-symptom',
    seriesId: 'menopause-basic',
    seriesOrder: 5,
    searchIntent: '질문',
    targetReader: '50대~60대',
    riskLevel: 'MEDIUM',
    reviewMode: 'RISK_SENTENCES',
    imageNeeded: 'REQUIRED',
    ctaTarget: '/community/menopause',
    internalLinks: ['hot-flash-how-long', 'when-does-menopause-start'],
    whyNow: 'menopause-basic 완결. "끝이 있다"가 이 시리즈의 결론이다',
    notes: '희망 톤으로 닫되 과장하지 않는다',
  },
  {
    day: 30,
    title: '갱년기에 운동을 다시 시작하며',
    slug: 'restart-exercise-menopause',
    cluster: 'daily',
    seriesId: 'body-change',
    seriesOrder: 5,
    searchIntent: '방법',
    targetReader: '40대 후반~50대',
    riskLevel: 'LOW',
    reviewMode: 'SUMMARY_ONLY',
    imageNeeded: 'OPTIONAL',
    ctaTarget: '/community/menopause',
    internalLinks: ['walking-minutes-50s', 'menopause-joint-pain-exercise'],
    whyNow: 'body-change 완결. 30일 큐를 커뮤니티 전환으로 닫는다',
    notes: '운동 프로그램을 제시하지 않는다. 다시 시작하는 마음까지가 범위다',
  },
]
